plugins {
    id 'java'
    id 'application'
}

group = "${projectGroup}"
version = "${projectVersion}"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(javaVersion)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation libs.jackson.databind
}

application {
    mainClass = applicationMainClass
}

jar {
    archiveBaseName.set("${projectName}")
    archiveClassifier.set('')
    archiveVersion.set('')
    manifest {
        attributes 'Main-Class': applicationMainClass
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs += ['-parameters']
}
