name: "Project Build"
run-name: "[📦]: Project Build #${{ github.run_number }}"
on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: "[🚀] Release"
    runs-on: ubuntu-latest
    steps:
      - name: "[📦] Checkout"
        uses: actions/checkout@v6

      - name: "[📥] Get Project Info"
        id: project_info
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: gradle.properties
          properties: version javaVersion

      - name: "[⚙️] Set up Java"
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ steps.project_info.outputs.javaVersion }}

      - name: "[⚙️] Set up Gradle"
        uses: gradle/actions/setup-gradle@v6

      - name: "[🔨] Build artifact"
        run: |
          chmod +x gradlew
          ./gradlew build
          ls -la build/libs/

      - name: "[🚀] Release"
        uses: Xikaro/game-publish@3.4.0
        with:

          github-name: ${{ needs.project_info.outputs.version }}
          github-tag: ${{ needs.project_info.outputs.version }}
          github-generate-changelog: true
          github-draft: false
          github-token: ${{ secrets.GITHUB_TOKEN }}

          files: ${{ needs.project_info.outputs.projectName }}.jar

          name: ${{ needs.project_info.outputs.projectName }}
          version: ${{ needs.project_info.outputs.version }}

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail
